# Generated by Django 5.1.7 on 2025-03-19 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_task_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='time',
            new_name='date',
        ),
    ]
