# Generated by Django 5.1.7 on 2025-03-19 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_time_task_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='author',
            new_name='user',
        ),
    ]
